version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/benchmark'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/examples/basic'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/examples/netlify'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/examples/nextjs'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/examples/typescript'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/examples/vercel'
    schedule:
      interval: daily
