[build]
  base = "website"
  command = "npm run build && npm run export"
  publish = "website/src/out"

[[redirects]]
  from = "/guides"
  to = "/guides/getting-started"

[[redirects]]
  from = "/docs"
  to = "/docs/server"
