name: pr

on: [pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna run compile
      - run: npm ci
        working-directory: ./benchmark
      - run: npm link ../packages/light
        working-directory: ./benchmark
      - run: npm test
        working-directory: ./benchmark
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
