name: scheduled

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx linkinator https://light.js.org -r
